nightreads/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from nightreads.user_manager import urls as user_manager_urls
from nightreads.user_manager import views as user_views


urlpatterns = [
    url(r'^users/', include(user_manager_urls, namespace='users')),
    url(r'^admin/', admin.site.urls),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^$', user_views.IndexView.as_view(), name='index'),
    url(r'^faq/$', TemplateView.as_view(template_name='faq.html'), name='faq')
]

nightreads/user_manager/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'unsubscribe/', views.UnsubscribeView.as_view(), name='unsubscribe'),
    url(r'subscribe/', views.SubscribeView.as_view(), name='subscribe'),
    url(r'confirm/', views.ConfirmEmailView.as_view(), name='confirm')
]

nightreads/user_manager/models.py
from django.db import models
from django.contrib.auth.models import User

from nightreads.utils import TimeStampMixin
from nightreads.emails.models import Tag


class Subscription(TimeStampMixin):
    is_subscribed = models.BooleanField(default=False)
    user = models.OneToOneField(User)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.user.username

nightreads/user_manager/forms.py
from django.contrib.auth.models import User
from django.core.signing import BadSignature, SignatureExpired
from django import forms

from nightreads.emails.models import Tag
from . import user_service


class SubscribeForm(forms.Form):
    email = forms.EmailField()

    def clean(self):
        cleaned_data = super(SubscribeForm, self).clean()
        all_tag, _ = Tag.objects.get_or_create(name='all')
        cleaned_data['tags'] = [all_tag, ]
        return cleaned_data


class UnsubscribeForm(forms.Form):
    email = forms.EmailField()


class ConfirmEmailForm(forms.Form):
    user = forms.IntegerField()
    subscribe = forms.IntegerField()
    code = forms.CharField(max_length=80)

    def clean_subscribe(self):
        value = bool(self.cleaned_data['subscribe'])
        self.cleaned_data['subscribe'] = value
        return value

    def clean(self):
        cleaned_data = super(ConfirmEmailForm, self).clean()
        if self.errors:
            return cleaned_data
        user_id = cleaned_data['user']
        code = cleaned_data['code']
        for_subscription = cleaned_data['subscribe']
        user = User.objects.filter(id=user_id).first()
        if not user:
            raise forms.ValidationError('Invalid Link')
        self.cleaned_data['user'] = user
        try:
            user_service.validate_key(key=code, user=user,
                                      for_subscription=for_subscription)
        except BadSignature:
            raise forms.ValidationError('Invalid Link')
        except SignatureExpired:
            raise forms.ValidationError('Link expired, please regenerate')
        return cleaned_data

nightreads/user_manager/views.py
from django.views.generic import View, FormView
from django.http import JsonResponse
from django.shortcuts import render

from .forms import SubscribeForm, UnsubscribeForm, ConfirmEmailForm
from . import user_service


class IndexView(View):
    form_class = SubscribeForm
    template = 'user_manager/index.html'

    def get(self, request):
        return render(request, self.template, {'form': self.form_class})


class SubscribeView(View):

    form_class = SubscribeForm

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            tags = form.cleaned_data['tags']
            user = user_service.get_or_create_user(email=email)
            is_updated = user_service.update_user_tags(user=user, tags=tags)
            if is_updated:
                key = user_service.generate_key(user=user)
                user_service.send_confirmation_email(
                    request=request, user=user, key=key)
                return JsonResponse({'status': 'Email sent'})
            return JsonResponse({'status': 'No tags updated'})
        return JsonResponse({'errors': form.errors})


class UnsubscribeView(FormView):
    form_class = UnsubscribeForm
    template_name = 'user_manager/unsubscribe.html'

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user = user_service.get_user(email=email)
        if not user:
            return JsonResponse({'error': 'User Not Found'})
        key = user_service.generate_key(user=user, for_subscription=False)
        user_service.send_confirmation_email(
            request=self.request, user=user, key=key, for_subscription=False)
        return JsonResponse({'status': 'Email sent'})

    def form_invalid(self, form):
        return JsonResponse({'errors': form.errors})


class ConfirmEmailView(View):

    form_class = ConfirmEmailForm

    def get(self, request):
        form = self.form_class(request.GET)
        if form.is_valid():
            is_subscribed = form.cleaned_data['subscribe']
            user = form.cleaned_data['user']
            user_service.update_subscription(user=user, status=is_subscribed)
            if is_subscribed:
                return JsonResponse({'status': 'Subscribed'})
            else:
                return JsonResponse({'status': 'Unsubscribed'})
        return JsonResponse({'errors': form.errors})

nightreads/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Nightreads</title>
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.min.css">
  <link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.min.js"></script>
</head>
<body>
<div class="pusher">
{% block body%}
{% endblock %}
  <div class="ui inverted vertical center aligned footer segment">
    <div class="ui text container">
      <div class="ui inverted">
          <p><a href="{% url 'faq' %}">FAQ</a> | <a href="{% url 'users:unsubscribe' %}">Unsubscribe</a> | <a href="http://slack.devup.in">Join Devup Slack</a> | <a href="//github.com/avinassh/nightreads">Built with &#x1F40D;</a> | <a href="https://twitter.com/devupin"><i class="twitter icon"></i></a></p>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
console.log(`                     @@@@@@ @
                   @@@@     @@
                  @@@@ =   =  @@
                 @@@ @ _   _   @@
                 @@@ @(0)|(0)  @@
                @@@@   ~ | ~   @@
                @@@ @  (o1o)    @@
               @@@    #######    @
               @@@   ##{+++}##   @@
              @@@@@ ## ##### ## @@@@
              @@@@@#############@@@@
             @@@@@@@###########@@@@@@
            @@@@@@@#############@@@@@
            @@@@@@@### ## ### ###@@@@
             @ @  @              @  @
               @                    @`)
console.log('gnu, if you see this, come home :)')
</script>
{% block javascript %}{% endblock %}
</body>
</html>

nightreads/templates/faq.html
{% extends 'base.html' %}

{% block body %}
  {% include 'masthead.html' %}
  <div class="ui inverted vertical center aligned segment">
    <div class="ui text container">
      <div class="ui inverted segment">
        <h2 class="ui inverted header">FAQ</h2>
      </div>
    <div class="ui inverted segment">
      <div class="ui inverted relaxed divided list">
        <div class="item">
          <div class="content">
            <p>Where do I provide feedback, suggestions or report bugs?</p>
            <p>For feedback and suggestions, use this <a href="http://goo.gl/forms/lb8i7Le3H4MfNUzv2">Google Form</a>. For bug reports, use <a href="https://github.com/avinassh/nightreads/issues">Github Issues</a>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

nightreads/templates/masthead.html
<div class="ui inverted vertical masthead center aligned segment">
  <div class="ui text container">
    <h1 class="ui inverted header">
      <a href="{% url 'index' %}">Nightreads</a>
    </h1>
    <h2>A good read before a good night's sleep, everyday.</h2>
  </div>
</div>

nightreads/templates/user_manager/index.html
{% extends 'base.html' %}

{% block body %}
  {% include 'masthead.html' %}
  <div class="ui inverted vertical center aligned segment">
    <div class="ui text container">
      <div class="ui inverted segment">
        <form class="ui inverted form" method="POST" action="{% url 'users:subscribe' %}">
          {% csrf_token %}
          {% for field in form %}
            <div class="field">
              {{ field.label_tag }}
              {{ field }}
            </div>
          {% endfor %}
          <button class="ui button" type="submit">Submit</button>
          <div class="ui error message"></div>
        </form>
      </div>
    </div>
  </div>
  <div class="ui inverted vertical center aligned segment">
    <div class="ui text container">
      <div class="ui inverted">
          <h2>What is Nightreads?</h2>
          <p>Each night we will email you a link to an interesting read. The links will never contain any news. (There are <a href="http://lobste.rs">plenty</a> <a href="https://news.ycombinator.com">of</a> <a href="https://www.reddit.com/r/programming">places</a> already where you can find your fix of latest tech news.)
          <p>You can suggest us interesting links via <a href="https://twitter.com/devupin">Twitter</a>, <a href="http://scr.im/avii">Email</a> or <a href="http://slack.devup.in">join</a> our <a href="https://dev-s.slack.com">Devup Slack Team</a>. We plan to build a web interface to manage this in future.</p>
          <p>Nightreads was originally started by our beloved member <a href="https://dev-s.slack.com/team/gnu">@gnu</a> in Devup Slack.</p>
      </div>
    </div>
  </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
  $('.ui.dropdown').dropdown();
  $('.ui.form')
  .form({
    fields: {
      email: {
        identifier: 'email',
        rules: [
          {
            type   : 'email',
            prompt : 'Please enter your email'
          }
        ]
      }
    }
  });
</script>
{% endblock %}

nightreads/templates/user_manager/subscribe.html
Thank you for subscribing to Nightreads. To confirm your subscription, please click on the following link to verify your email:

<a href="{{ url }}">Confirm Subscription</a> 

Cheers,
Nightreads

nightreads/templates/user_manager/subscribe_email.html
Thank you for subscribing to Nightreads. To confirm your subscription, please click on the following link to verify your email:

<a href="{{ url }}">Confirm Subscription</a> 

Cheers,
Nightreads

nightreads/templates/user_manager/unsubscribe.html
{% extends 'base.html' %}

{% block body %}
  {% include 'masthead.html' %}
  <div class="ui inverted vertical center aligned segment">
    <div class="ui text container">
      <div class="ui inverted segment">
      <form class="ui inverted form" method="POST" action="{% url 'users:unsubscribe' %}">
        {% csrf_token %}
        <div class="field">
          <label>Email</label>
          <input type="email" name="email" placeholder="Enter your email to unsusbcribe :(">
        </div>
        <button class="ui button" type="submit">Submit</button>
        <div class="ui error message"></div>
      </form>
      </div>
    </div>
  </div>
<script type="text/javascript">
  $('.ui.form')
  .form({
    fields: {
      email: 'email'
      }
  });
</script>
{% endblock %}

nightreads/templates/user_manager/unsubscribe_email.html
Sorry to let you go. To cancel your subscription, please click on the following link to verify:

<a href="{{ url }}">Cancel Subscription</a> 

Cheers,
Nightreads